---
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: arc
    steps:
      - uses: actions/checkout@master
      - name: Tests
        run: |
          df -h
          pwd
          cat /etc/os-release
          whoami
